/*
 * Extole consumer-api
 * This is a sample generated doc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@extole.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extole.consumer.rest.model;

import java.util.*;
import java.time.*;
import java.math.*;
import com.extole.consumer.*;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.extole.consumer.rest.model.QualityRuleResult;
import java.util.ArrayList;
/**
 * QualityResults
 */


public class QualityResults {
  /**
   * Gets or Sets score
   */
  public enum ScoreEnum {
    ERROR("ERROR"),
    LOW("LOW"),
    HIGH("HIGH");

    private String value;

    ScoreEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ScoreEnum fromValue(String text) {
      for (ScoreEnum b : ScoreEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("score")
  private ScoreEnum score = null;

  @JsonProperty("quality_rule_results")
  private List<QualityRuleResult> qualityRuleResults = null;

  public QualityResults score(ScoreEnum score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @Schema(description = "")
  public ScoreEnum getScore() {
    return score;
  }

  public void setScore(ScoreEnum score) {
    this.score = score;
  }

  public QualityResults qualityRuleResults(List<QualityRuleResult> qualityRuleResults) {
    this.qualityRuleResults = qualityRuleResults;
    return this;
  }

  public QualityResults addQualityRuleResultsItem(QualityRuleResult qualityRuleResultsItem) {
    if (this.qualityRuleResults == null) {
      this.qualityRuleResults = new ArrayList<>();
    }
    this.qualityRuleResults.add(qualityRuleResultsItem);
    return this;
  }

   /**
   * Get qualityRuleResults
   * @return qualityRuleResults
  **/
  @Schema(description = "")
  public List<QualityRuleResult> getQualityRuleResults() {
    return qualityRuleResults;
  }

  public void setQualityRuleResults(List<QualityRuleResult> qualityRuleResults) {
    this.qualityRuleResults = qualityRuleResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QualityResults qualityResults = (QualityResults) o;
    return Objects.equals(this.score, qualityResults.score) &&
        Objects.equals(this.qualityRuleResults, qualityResults.qualityRuleResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(score, qualityRuleResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QualityResults {\n");
    
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    qualityRuleResults: ").append(toIndentedString(qualityRuleResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
