/*
 * Extole consumer-api
 * This is a sample generated doc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@extole.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extole.consumer.rest.model;

import java.util.*;
import java.time.*;
import java.math.*;
import com.extole.consumer.*;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonCreator;
/**
 * SubmitEventResponse
 */


public class SubmitEventResponse {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("token")
  private String token = null;

  @JsonProperty("cookie_consent")
  private String cookieConsent = null;

  public SubmitEventResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SubmitEventResponse token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @Schema(description = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public SubmitEventResponse cookieConsent(String cookieConsent) {
    this.cookieConsent = cookieConsent;
    return this;
  }

   /**
   * Get cookieConsent
   * @return cookieConsent
  **/
  @Schema(description = "")
  public String getCookieConsent() {
    return cookieConsent;
  }

  public void setCookieConsent(String cookieConsent) {
    this.cookieConsent = cookieConsent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitEventResponse submitEventResponse = (SubmitEventResponse) o;
    return Objects.equals(this.id, submitEventResponse.id) &&
        Objects.equals(this.token, submitEventResponse.token) &&
        Objects.equals(this.cookieConsent, submitEventResponse.cookieConsent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, token, cookieConsent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitEventResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    cookieConsent: ").append(toIndentedString(cookieConsent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
